# ~/.config/aichat/config.yaml
# For a config example, see https://github.com/sigoden/aichat/blob/main/config.example.yaml
# Available models: https://github.com/sigoden/aichat/blob/main/models.yaml

model: openai:gpt-4o-mini
temperature: 1
keybindings: vi
editor: nvim
wrap: auto
clients:
  - type: claude
    name: anthropic
  - type: openai
  - type: openai-compatible
    name: pplx
    api_base: https://api.perplexity.ai
    models:
      - name: sonar-pro
      - name: sonar
