#!/bin/sh
#
# !ln -s %:p ~/.xinitrc
#

WM="i3"

# disable trackpad while typing
# syndaemon -t -k -i 2 -d &
# -i 2: sets the idle time to 2 seconds. The idle time specifies how many seconds after the last key-press before enabling touchpad again.
# -t: tells the daemon not to disable mouse movement when typing and only disable tapping and scrolling
# -k: ignore modifier keys when monitoring keyboard activity
# -d: starts as a daemon

# Dvorak keyboard
setxkbmap -variant dvorak

# Xmodmap
xmodmap ~/.Xmodmap

# activating numlock X11
numlockx

# Wallpaper
# eval `cat ~/.fehbg`

if [ "$(hostname)" == "turing" ]; then
  # Config dual monitor setup with DP-4 as primary
  xrandr --output HDMI-0 --auto --output DP-4 --left-of HDMI-0 --mode 2560x1440 --rate 144 --primary

  # Restore previously saved wallpaper settings
  nitrogen --restore
fi

#   xrandr --output LVDS --auto --primary
#   xrandr --output VGA1 --auto --left-of LVDS
#     xrandr --output LVDS --auto --output HDMI-0 --right-of LVDS #--primary
#     xrandr --output LVDS --primary
#   xrandr --output eDP1 --auto --output HDMI1 --right-of eDP1 #--primary
#   xrandr --output eDP1 --primary

## windows manager ---------------
exec $WM
